version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: cloudmart-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  product-service:
    build: .
    container_name: cloudmart-product-service
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/cloudmart

volumes:
  mongo-data:
