apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmart-ui
  labels:
    app: cloudmart-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudmart-ui
  template:
    metadata:
      labels:
        app: cloudmart-ui
    spec:
      containers:
        - name: ui
          image: bavithran174/cloudmart-ui:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
