apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.cloudmart.com
      secretName: frontend-tls
  rules:
    - host: www.cloudmart.com
      http:
        paths:
          - path: /
            pathType: Prefix
              backend:
                service:
                  name: cloudmart-ui
                  port:
                    number: 80
