# 1. Namespace definition
apiVersion: v1
kind: Namespace
metadata:
  name: cloudmart-product
---
# 2. Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmart-product
  namespace: cloudmart-product
  labels:
    app: cloudmart-product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudmart-product
  template:
    metadata:
      labels:
        app: cloudmart-product
    spec:
      containers:
        - name: product-service
          image: bavithran174/cloudmart-product:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: PORT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: product-service-secret
                  key: MONGO_URI